server:
  port: 8761

eureka:
  instance:
    hostname: 172.17.0.1
    preferIpAddress: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://172.17.0.1/eureka/