server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.49.2
    preferIpAddress: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://192.168.49.2/eureka/